### ISSUE TITLE
Feature: User can view a random joke

### ISSUE THREAD

**Issue by maryalenn** [maryalenn/ajax-project#1]
## ⚙️ Feature

> Display a randomly generated joke from the JokeAPI
https://v2.jokeapi.dev/

## 📐 Functionality

User is introduced to the "Just for Laughs" app, greeted with a new joke, option to rate the joke, and to generate a new joke

## 🖼️ Wireframes

https://www.figma.com/file/ByQAHxZ89PQ6jeMTYRF6QE/AJAX-API-Project---Marya-Chuong?node-id=1%3A3
![image](https://user-images.githubusercontent.com/97073517/172289685-813a80a2-785a-4299-a599-31bd01cef31c.png)
![image](https://user-images.githubusercontent.com/97073517/172289719-827a1db7-f3f6-4343-864e-44e8898a2bbe.png)

## ✅ Task List

- [x] Create html page using dummy data
- [x] Create CSS for all styling
- [x] Add hover & click style changes to buttons in CSS
- [x] Create javascript file and add eventListeners to buttons
- [x] Add a `currentJoke` id to the div holding the generated joke
- [x] Query the DOM for the `#currentJoke` element
- [x] Create a new XMLHttpRequest() object.
- [x] open() the xhr object to send a 'GET' request to 'https://v2.jokeapi.dev/joke/Any?blacklistFlags=racist,sexist,explicit'
- [x] Set the responseType
- [x] Listen for the 'load' event on the xhr object in order to:
  - [x] log the of the xhr object to the console
  - [x] log the response of the xhr object to the console
  - [x] append the xhr object to the `#currentJoke` element
  - [x] send() the request to begin loading the data from the server.
  - [x] test that a new joke is added on refresh

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by maryalenn** [comment]
- [ ] Need to adjust CSS to address scrollbars for longer length jokes. Reviewing best solutions.

![Ajax - Feature 1](https://user-images.githubusercontent.com/97073517/174466742-bf0de5bc-1d66-4622-98bf-9a676dc5b217.gif)
